### ISSUE TITLE
feat: Provide .net new template

### ISSUE THREAD

**Issue by tomkerkhove** [buehler/dotnet-operator-sdk#133]
I typically don't like to ask these kind of things but are you planning on providing a sample project, or even a .NET template?

The documentation is good on how to get started, but always great if you have a reference project or scaffold option.

**Comment by buehler** [comment]
I want to provide a .NET template at some point, this is a good idea!
There is a demo project located @ https://github.com/buehler/dotnet-operator-sdk/tree/master/tests/KubeOps.TestOperator

That's the operator I use for local development / testing which runs against my docker-kubernetes.

**Comment by tomkerkhove** [comment]
Cool, thanks!

**Comment by buehler** [comment]
Template ideas:

- Full operator solution (empty): create .sln with src / test folder, as well as common config and nuke build but without implementation
- Full operator solution with demo code: create whole solution like above, but with some demo code
- Operator project (empty)
- operator project with demo code
- operator test project
- file template for webhooks
- file templates for controllers

**Comment by tomkerkhove** [comment]
I'm happy to use the operator project with demo code option for my exploration for promitor.io

**Comment by buehler** [comment]
I guess I'm going to introduce some breaking changes (like removing the "structured logger" stuff, since this is basic .net 5.0 now)
but as soon as I'm happy to release 3.0 I'm going to :-)

**Comment by tomkerkhove** [comment]
Awesome, thanks!

**Comment by buehler** [comment]
No problem :-) it's a fun project.

What do you think about #138 ? (I'd like to have your opinion)
The basic idea is to restructure the controllers (and possibly killing of the "controller base" class) in a way that they function like asp.net api controllers. so when an event happens (create/update/delete), a DI - scope is created and the specific method is called.
this way, it would feel like normal asp.net with scoped instances of dependencies.
also, it would kind of kill off the need for the event queue since the controller could run in parallel and do not need to wait for one another. they would be scoped and instantiated for each event.

**Comment by tomkerkhove** [comment]
That would be super great if you ask me!

**Comment by tomkerkhove** [comment]
Awesome, will use this for my POC!
