### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by sebagomez** [buehler/dotnet-operator-sdk#190]
Hey, you're hard to find so this is the only way I found.

I think you have a great thing here, as the matter of fact, I have kind of the same :)
I'm the maintainer of a similar project where I want to have C# (or .NET) developers easily write Kubernetes Operators. You can take a look at my project [here](https://github.com/containersolutions/dotnet-operator-sdk).

I was wondering if you wanted to join for a quick chat and discuss the future of .NET in the Kubernetes Operators world.

You can reply this issue and/or reach out directly to me by email. 
Cheers

**Comment by buehler** [comment]
Hey @sebagomez 
:-) 
Thank you!
I had a very brief look at the repository which looks nice!

Yea, I'm totally in for some discussion if you want to. I copied your issue over to the "discussions" of GitHub if you don't mind.

I'm going to close this issue here and we may further discuss the matter in https://github.com/buehler/dotnet-operator-sdk/discussions/191.

Cheers
