### ISSUE TITLE
Requeuing events piles up entities in queue

### ISSUE THREAD

**Issue by buehler** [buehler/dotnet-operator-sdk#280]
From https://github.com/buehler/dotnet-operator-sdk/discussions/277

**Describe the bug**
When using the "requeue in" feature of the SDK, if one uses "not modified" to requeue events after a certain period, it can lead to piled up requeued events since there is no check if the current uuid (resource) is already queued.

**To Reproduce**
Use requeue feature :)

**Expected behavior**
The requeue "queue" should only contain one copy of the resource (entity) in question.

**Comment by erin-allison** [comment]
I figured out how to implement this with a single Subject in Reactive, but since `ResourceWatcher<T>` manages three independent observables, this won't work out of the box. I think it will require a refactor to make all those into one.

```csharp
var watcher = events
    .GroupBy(envelope => envelope.Item.Id)
    .Select(group =>
    {
        return group
            .Select(envelope =>
                envelope.Delay is null
                    ? Observable.Return(envelope)
                    : Observable.Return(envelope with {Delay = null}).Delay(envelope.Delay.Value))
            .Switch();
    })
    .Merge()
    .Do(envelope => Log.Information("Processing Envelope {@Envelope}", envelope));

watcher.Subscribe();

void Queue(int id, int delay)
{
    events!.OnNext(
        new RequeueEnvelope(
            new Item(id),
            TimeSpan.FromSeconds(delay)));
}

Queue(1, 10);
Queue(1, 5);
Queue(1, 1);
Queue(1, 2);
Queue(1, 3);
Queue(1, 4);

await Task.Delay(5000);

Queue(1, 1);
```

Some pretty minimal sample code here, but what this ends up with is the first batch of items gets grouped such that each time I queue a new item, it replaces any previous items w/ the same ID on the observable. As a result, when I run this, I end up getting two lines of output: one which is 4 seconds after the first batch of calls to queue, and another which is 6 seconds afterwards (5 second delay + a 1 second delay in the queue)

```
2022-02-17 10:28:57.467 -06:00 [Information] Processing Envelope RequeueEnvelope {Item=Item {Id=1}, Delay=null, QueuedAt=02/17/2022 10:28:53}
2022-02-17 10:28:59.448 -06:00 [Information] Processing Envelope RequeueEnvelope {Item=Item {Id=1}, Delay=null, QueuedAt=02/17/2022 10:28:58}
```
