### ISSUE TITLE
Remove the Dotnet Kubernetes Client

### ISSUE THREAD

**Issue by buehler** [buehler/dotnet-operator-sdk#435]
Remove the custom implementation (with generics) and use the original client. They have generics now. Therefore the logic must not be implemented twice.

**Comment by Silvenga** [comment]
How did I miss that? Yeah, this would be a good opportunity!

**Comment by buehler** [comment]
No worries :-D just wrote the "issue" this morning.

**Comment by buehler** [comment]
Would you mind to take upon this task?

**Comment by Silvenga** [comment]
Actually not sure if it'll be worth moving to the generic API - https://github.com/kubernetes-client/csharp/pull/744/files#diff-b6ffdded30c31747bbe5fd118533176288995b595670672553915eb7976fbaa2

The project would need to implement a similar abstraction to https://github.com/buehler/dotnet-kubernetes-client, since the generics API requires knowing the object types during the construction of the client, where dotnet-operator-sdk is naturally more lazy.

```
var genericPods = new GenericClient(client, "", "v1", "pods");
await genericPods.CreateNamespacedAsync(
    new V1Pod()
    {
        Metadata = new V1ObjectMeta { Name = podName, },
        Spec = new V1PodSpec
        {
            Containers = new[] { new V1Container() { Name = "k8scsharp-e2e", Image = "nginx", }, },
        },
    },
    namespaceParameter);
var pods = await genericPods.ListNamespacedAsync<V1PodList>(namespaceParameter)
```

**Comment by erin-allison** [comment]
I'm interested in why they didn't put the type argument on the class... if they did that, we could handle this with a factory.

On a cursory inspection, I agree with @Silvenga in that it may not be worth the refactor.

**Comment by Silvenga** [comment]
Yeah, I'm a little confused too, but to be honest, the new V8 API moved so much, it's hard to discover where things went. If there's another way they didn't document anywhere, I haven't found it.

Regardless, there's a lot of changes to move from JSON.NET to System.Text.Json e.g. JsonDiffer only supports JSON.NET. I'm going to focus on at least upgrading to the V7.2 API (since V8 was only released 4 days ago). Aka upgrading [dotnet-kubernetes-client](https://github.com/buehler/dotnet-kubernetes-client) 2.1.12.
