### ISSUE TITLE
Deployment of operator as pod to cluster

### ISSUE THREAD

**Issue by LukaDevic** [buehler/dotnet-operator-sdk#474]
**Describe the missing piece of documentation**
Describe what you miss in the docs.

Can you add in documentation guide how to deploy operator to cluster via kubectl, flux trough Github repository and directly in Rancher. 

I can run operator from visual studio and it works properly with the cluster, but cant deploy it to cluster as a deployment/pod. Operator pod which is created in cluster is restarting non stop without end.

**Comment by buehler** [comment]
Hey @LukaDevic 

Actually, the operator build process constructs a "kustomize" config. So, for example, when looking at the install config of https://github.com/WirePact/k8s-operator/blob/main/Operator/config/install/kustomization.yaml, you can use kustomize to create all your definitions and then apply them.

https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/

Here you should find the required resources.

This is no matter of kubeops itself since the deployment is a feature of Kubernetes
