### ISSUE TITLE
Allow entities to specify spec property of CRD as required

### ISSUE THREAD

**Issue by dvojak-cz** [buehler/dotnet-operator-sdk#519]
**Is your feature request related to a problem? Please describe.**
I need to create CRD that will have spec section required.

**Describe the solution you'd like**
Create new attribute for marking entity. This attribute will mark whether or not the spec section should be required in the CRD.

**Comment by dvojak-cz** [comment]
PR: #520

**Comment by buehler** [comment]
Would it be "breaking" to just make all "spec" required? I don't think so, since using the custom resource object (base class) already uses the spec object.

**Comment by dvojak-cz** [comment]
I have overcome it in my project this way. For me it makes sense, but the API will not stay totally the same, it's not an opt-in change.
- For clear code, I would just mark it as required.
- For not changing API I would add a new attribute.

What about adding a new attribute for now and when it's time to release a new Major version add the required attribute?
I can make another pull request so that it won't be forgotten.

**Comment by buehler** [comment]
wdyt about this?
@tomasfabian @erin-allison 

I'd go for the change to make spec required when the custom class with spec and status is used. (Instead of a new attribute). And it is not a breaking change in my opinion. (Well... technically it is, but it is fixing a bug in my opinion)

**Comment by tomasfabian** [comment]
Hello @buehler @dvojak-cz @anekdoti @erin-allison,
I think that deciding the optionality of the Spec based on its type's nullability is a good idea instead of using a required attribute.

Regarding the patch vs breaking change dilemma in semversioning I would vote for a major change here since in .NET it is possible to use package version ranges such as exclusive exact range (1.0,2.0). This could break some brave continuous delivery pipelines IMO.

**Comment by buehler** [comment]
Fair point, and thanks for the input!
