### ISSUE TITLE
[bug]: Building the project throws "An error occurred trying to start process '/operator/cfssl'"

### ISSUE THREAD

**Issue by jhested** [buehler/dotnet-operator-sdk#586]
### Describe the bug

Creating a new project fresh from the template results in errors when trying to build the project locally and through CI

Generating CA certificate.
2>Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/operator/cfssl' with working directory 'C:\git\EPE\sqlIdentity-operator\src\Operators\api\Operators.SqlIdentities\config\operator'. The system cannot find the file specified.
2>   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
2>   at KubeOps.Operator.Commands.CommandHelpers.CertificateGenerator.GenCertAsync(String arguments, String outputFolder, CancellationToken cancellationToken)
2>   at KubeOps.Operator.Commands.CommandHelpers.CertificateGenerator.CreateCaCertificateAsync(String outputFolder)
2>   at KubeOps.Operator.Commands.Generators.OperatorGenerator.OnExecuteAsync(CommandLineApplication app)
2>   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
2>   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
2>   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
2>--- End of stack trace from previous location ---
2>   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
2>   at Program.<Main>$(String[] args) in C:\git\EPE\sqlIdentity-operator\src\Operators\api\Operators.SqlIdentities\Program.cs:line 8
2>   at Program.<Main>(String[] args)

### To reproduce

1. dotnet new install KubeOps.Templates::7.4.2
2. dotnet new operator -n DemoOperator
3. dotnet build DemoOperator.csproj

### Expected behavior

Project builds without errors

**Comment by molson504x** [comment]
I'm also having this issue.

**Comment by molson504x** [comment]
So the issue is that there's an assumption that `cfssl` is going to be found at `/operator/cfssl`, which on some file systems is not an option.  I feel like the problem is the leading `/` which means that directory path is found at the root directory.  This assumption is based on the directory structure of the generated Dockerfile, but is bad for local file systems.

The location of the cfssl files can be set using the environment variable `CFSSL_EXECUTABLES_PATH` (note - this is not documented).  This is hard-coded in `src/KubeOps/Operator/Commands/CommandHelpers/CertificateGenerator.cs` in the `CreateCaCertificateAsync` function

``` cs
    public async Task CreateCaCertificateAsync(string outputFolder)
    {
        if (!_initialized)
        {
            var cfsslFolder = Environment.GetEnvironmentVariable("CFSSL_EXECUTABLES_PATH") ?? "/operator";
            _cfssl = $"{cfsslFolder}/{_cfssl}";
            _cfssljson = $"{cfsslFolder}/{_cfssljson}";
            await PrepareExecutables();
            _initialized = true;
        }
        // I removed the rest since it's not relevant to this issue
    }
```

So in my case, if I just place cfssl in the project directory, I just run `export CFSSL_EXECUTABLES_PATH="$(pwd)/cfssl"` (assuming I'm in my project directory).  I also downloaded cfssl and cfssljson and placed them into that directory...  and then the build works fine.

**Comment by ewassef** [comment]
@buehler @virgilp ^^ this seems to be due to https://github.com/buehler/dotnet-operator-sdk/pull/568 . Unfortunately, my shim didn't allow the action to be called before this method
