### ISSUE TITLE
[feature]: Minimal API server rather than including full ASP.NET Core for webhook operator

### ISSUE THREAD

**Issue by wizpresso-steve-cy-fan** [buehler/dotnet-operator-sdk#660]
### Is your feature request related to a problem? Please describe.

We are using [Cocona](https://github.com/mayuki/Cocona) for building our own operator with advanced CLI support. Basic hosted service works out of the box, but for webhook operators, the full ASP.NET core is imported. In order to avoid having to manage two hosted services (we are wrapping Cocona atop of ASP.NET Core WebApplication this way) it is better to strip the 

### Describe the solution you would like

Implement the minimal subset of ASP.NET Core such that the web hook should work well.

**Comment by buehler** [comment]
hey @wizpresso-steve-cy-fan, do you know how to have such a minimal implementation?

**Comment by buehler** [comment]
addition: it kind of is required for the local tunnel magic :-) however, there can be workarounds for that too :)

**Comment by wizpresso-steve-cy-fan** [comment]
@buehler what are the workarounds?

**Comment by buehler** [comment]
I do not know. For the asp part, there are no (feasible) workarounds. IMO it makes perfectly sense to create an asp application, since everything with certificates and other rather complicated matters is automatically taken care of.

However, you may implement the webhooks without mvc controller support, you can glance at the code of the controllers here and implement the minimal api server by yourself.

I do not have any plans to support another server since kestrel is kind of the minimal api server that I see.
