### ISSUE TITLE
feat: allow complex status objects

### ISSUE THREAD

**Issue by TeunKooijman** [buehler/dotnet-operator-sdk#78]
I'm not sure if this is working as intended, but the following code thus results in an infinite loop:

```
protected override async Task<TimeSpan?> Updated(MyEntity resource)
{
    resource.Status.Progressing = true;
    Client.UpdateStatus(resource);

    //Even if I do nothing here, just switch the states around, it will still re-trigger the Updated event asynchronously.
    await base.Updated(resource);

    resource.Status.Progressing = false;
    Client.UpdateStatus(resource);

    //The second UpdateStatus can yield in a 409 conflict response. Pretend that's fixed by Client.Get()'ing the up to date resource and applying the state change to that again, before re-calling Client.UpdateStatus.
}

```

I understand that there's also a StatusModified event callback, of which the docs state:
`// "StatusModified" (i.e. when only the status was updated)`

Is Updated meant to be called when we only update the status object of the entity/resource?

**Comment by TeunKooijman** [comment]
Our Status object is a complex type. I have simplified it in the original post, but I fear that simplification might actually cause things to go right. Our status object (serialized) will look something along the lines of:

```
{
   "conditions": [
      {"type": "Progressing", "status": true, "lastModifiedTime": "2020-10-23T17:21:23.000"},
      {"type": "Healthy", "status": false, "lastModifiedTime": "2020-10-23T17:21:23.000"},
      {"type": "Degraded", "status": false, "lastModifiedTime": "2020-10-23T17:21:23.000"},
   ]
}
```

Line 79 on [ResourceCache](https://github.com/buehler/dotnet-operator-sdk/blob/master/src/KubeOps/Operator/Caching/ResourceCache.cs) suggests that the detection of the change being "just a status change" is limited to properties directly under Status. Is that assumption correct? If so, would it be possible to extend that detection to handle changes deeper inside a complex object?

**Comment by buehler** [comment]
For the first post: Updated is called when something in the object has changed. StatusUpdated is called when only the subobject (status) has changed.
For the second post: Your assumption is correct. As I thought, status was a simple object. I didn't found any other documentation or example from kubernetes itself or anywhere else that stated, that status should be a complex object.

It could be done to upgrade the cache logic of course. If this is not an antipattern with kubernetes.

Do you have any readings about the matter?

**Comment by buehler** [comment]
For the code you provided, I don't think this should be as you intend it to. Kubernetes operator functions should "kind of be atomic", in the sense that - for what I saw as examples and from kubebuilder and others - the operation runs and performs some task. To check if something is right now "executing", a "last processed" timestamp would be a better aproach.

One of the reasons being that if your operator crashes during the processing part, maybe your resource never get out of the "processing" state.

**Comment by buehler** [comment]
I just tested it, it is not intended (and possible) to use complex status objects.
Everytime I tried to update a complex status object, some parts were not updated by kubernetes itself.
It seems that it's not intended to use. So I'd suggest to use plain simple objects on status as it is intended (at least by kubernetes v1.18)

**Comment by willemm** [comment]
The status object of a lot of standard Kubernetes objects are certainly complex objects.
Take for example the 'Pod' object.  It has a 'conditions' field which is an array of objects (with lastProbeTime, lastTransitionTime, type and status) and also another subobject containerStatuses.

**Comment by buehler** [comment]
Well, thanks @willemm :-)
Then I need to investigate this further.

**Comment by erin-allison** [comment]
> I understand that there's also a StatusModified event callback, of which the docs state:
> // "StatusModified" (i.e. when only the status was updated)
> 
> Is Updated meant to be called when we only update the status object of the entity/resource?

@willemm I actually ran into this myself too. I can see the `StatusModified` callback being thrown for built-in entities, but not anything defined by a CRD.

> For the first post: Updated is called when something in the object has changed. StatusUpdated is called when only the subobject (status) has changed.
> For the second post: Your assumption is correct. As I thought, status was a simple object. I didn't found any other documentation or example from kubernetes itself or anywhere else that stated, that status should be a complex object.
> 
> It could be done to upgrade the cache logic of course. If this is not an antipattern with kubernetes.

Status should (and can be) whatever the resource defines at as. I think the simple object comes from how `IKubernetes` requires the Status property to be of type `object`, and nothing more complex, in order to use the `UpdateStatus` method.

In fact, I actually had to do not a small bit of funny business to support a typed status, but if the below referenced method signature can be updated to not specifically restrict to `object`, we should be fine. 

https://github.com/buehler/dotnet-kubernetes-client/blob/b2cc147c1cb3f6eaf5d85c4609ddae04d781f124/src/DotnetKubernetesClient/KubernetesClient.cs#L241-L242

The only thing Kubernetes checks for is that there is a property named "Status" when using the associated endpoint, as that is all that it will update on the resource.

(sample of what I had to do to support that)

```csharp
public abstract class CustomKubernetesEntityWithStatus<TSpec, TStatus> : CustomKubernetesEntity<TSpec, object>
        where TSpec : new() where TStatus : class, new()
{
  public new TStatus Status
  {
    get => base.Status as TStatus;
    set => base.Status = value;
  }
}
```

**Comment by erin-allison** [comment]
As far as avoiding having status updates trigger the Update call for CRDs, the best I can think of is run all the update calls through a function which compares the last seen object state with current, to determine if spec/meta or status changed (or both), and rerouting the request accordingly.

I'm not sure how that fares as far as scalability or performance when possibly comparing large objects quickly, but its what I got.

**Comment by buehler** [comment]
Hey @erin-allison 
Thank you for the investigation. I think there might be a solution to this matter.
I'll have a look at your suggestion :-)

Thanks!

**Comment by erin-allison** [comment]
So I did some more digging and it looks like you already do what I mentioned above:

> As far as avoiding having status updates trigger the Update call for CRDs, the best I can think of is run all the update calls through a function which compares the last seen object state with current, to determine if spec/meta or status changed (or both), and rerouting the request accordingly.

All events are run against a cache, and the comparison result against that cache is what determines the event call that is thrown. For some reason, though `StatusModified` isn't being used for any of my custom objects, only build-in Kubernetes types.

Upon stepping into `ResourceCache<TEntity>.CompareCache`, I can see where the logic issue lies.

https://github.com/buehler/dotnet-operator-sdk/blob/eb1ba60e8d01ff0f422969de56d116118be4879d/src/KubeOps/Operator/Caching/ResourceCache.cs#L66-L83

The comparison checks if the properties that differ are all direct children of "Status" (that's what the constant of that name resolves to). This falls through on any more complex objects, as the differences may lie more than 1 level deep.

![image](https://user-images.githubusercontent.com/75811601/103181854-80878e00-486b-11eb-9aa9-93d5685a1da0.png)

Additionally, I saw a case where when adding a status object (when there previously was none), the check would return `Modified` since the differing property was "Status", not one of its direct descendants.

![image](https://user-images.githubusercontent.com/75811601/103181947-71eda680-486c-11eb-9bdd-3671f8646161.png)

This should be an easy fix to see if `PropertyName` is "Status" or if `ParentPropertyName` is a period-separated string beginning with "Status", in addition to checking if `ParentPropertyName` is "Status"
